language: node_js
node_js:
- '5.1'
compiler: clang-3.6
env:
  matrix:
  - CXX=clang-3.6
  global:
    GH_REF: github.com/bluebirrrrd/ng2-budget.git
    secure: gfj3Zzh+8mY5OQj1N0jvtiPoqxuEo7FwSzmqsFhLweXTsm99JoStnIOXP367DmsgE/P7/uRLJbPWfD7YZ/np2eEVHtZe57mXRLIxWyc1wWMLe+ZgFYXFJ06gwqKYs7X9i+s647UuBYRdIRbHAwaLfuKw5JxtG5xR09K7YXI6vSUoo104l1ruONZ7jBAesSPItmiHzrYFfDpv2f1VOxtKJqyBs30qpkyLmCwjPAt/garXjNTfycsC8S30RruCHxH1f3Yi2DWam2F000wgQFEeNtTIj8RljwSEHXI/3L9rKCSeo9XjZoa/YEFyUNQDEeriHuRLeps0Bu5oR5JkGZm78PPbpuwDjlFQxrMei/ONaKaK+cDYl9UpeQaQWl7U3Trp3dNJIVi0lxOIF5Jza+t8BkA6oPbCepcl/UX345ssMeEZyMQxCv9S9MEzZmE67o02+THXG5kWb5wNHQ18dSlUIajRxXBgBqpeGwb3sNshLKaxmw+A6gFPnPKdBeCVVDJIGVbGasBOvuVYvE96IINAHSxK8CzpY+jkn/ymthUEPLlhT5QLj1A8JN6dwPYKO/fQdd+BZLAVNesg4KdksLk4UCqtQTA4CLgh9b5Mflt3883Nc8fRYLBRo7UI4lV+iCxvdB6lxrRNlXHVZRmi5e8gQbZVfdD6vHf+Edum+8kkGrY=
sudo: true
addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.6
    - ubuntu-toolchain-r-test
    packages:
    - clang-3.6
    - g++-4.8
before_install:
- sudo apt-get update
- sudo apt-get install -y libappindicator1 fonts-liberation
- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
- sudo dpkg -i google-chrome*.deb
install:
- npm i protractor karma-cli webpack typings webpack-dev-server -g
- npm i
- npm run lint
- npm run pree2e
before_script:
- npm start &
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- npm test
after_success:
  - make -e GH_REF=GH_REF GH_TOKEN=GH_TOKEN deploy 
